// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltrfbrgpmhjlnmvqwmeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0cmZicmdwbWhqbG5tdnF3bWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDY5NTEsImV4cCI6MjA2NDgyMjk1MX0.K_pPOmsu6UWZJEzPN396lKCjekfXaQsZlRZR3_kehlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);